var basketball = [
	{
		question : 'What NBA player scored 100 points on March 2, 1962?',
		choiceA : 'Wilt Chamberlain',
		choiceB : 'Bill Russell',
		choiceC : 'Kareem Abdul-Jabbar',
		correct : 'A',
	}, 
	{
		question : 'Who was the youngest player to score 10,000 points in the NBA?',
		choiceA : 'Michael Jordan',
		choiceB : 'Kobe Bryant',
		choiceC : 'Lebron James ',
		correct : 'C',
	}, 
	{
		question : 'What team owns the longest winning streak in NBA history?',
		choiceA : 'Lakers',
		choiceB : 'Bulls',
		choiceC : 'Heat',
		correct : 'A',
	}, 
	{
		question : 'How many games did Wilt Chamberlain foul out of during his 14 year NBA career?',
		choiceA : '11',
		choiceB : '0',
		choiceC : '55',
		correct : 'B',
	}, 
	{
		question : 'Which player did the Lakers draft twice?',
		choiceA : 'Kobe Bryant',
		choiceB : 'Elgin Baylor',
		choiceC : 'Magic Johnson',
		correct : 'B',
	}, 
	{
		question : 'Who is the youngest player in NBA history to record three triple-doubles?',
		choiceA : 'Luka Doncic',
		choiceB : 'Lebron James',
		choiceC : 'Michael Jordan',
		correct : 'A',
	}, 
	{
		question : 'Who was the first teenager in NBA history to score 20+ points in 10 consecutive games?',
		choiceA : 'Zion Williamson',
		choiceB : 'Lebron James',
		choiceC : 'Kobe Bryant',
		correct : 'A',
	}, 
	{
		question : 'Who was the first NBA player to test positive for COVID-19?',
		choiceA : 'Donovan Mitchell',
		choiceB : 'Jordan Clarkson',
		choiceC : 'Rudy Gobert',
		correct : 'C',
	}, 
	{
		question : 'What player won All-Star Game MVP, NBA MVP, and NBA Finals MVP awards in 2000?',
		choiceA : 'Kobe Bryant',
		choiceB : 'Shaquille O Neal' ,
		choiceC : 'Tim Duncan',
		correct : 'B',
	}, 
	{
		question : 'What are the Dallas Mavericks named after?',
		choiceA : 'Broadway Musical',
		choiceB : 'Novel',
		choiceC : 'Tv Show',
		correct : 'C',
	} 


];

var tv = [
	{
		question : 'What type of dog is Scooby Doo from the cartoon series, "Scooby Doo"?',
		choiceA : 'English Mastiff',
		choiceB : 'Great Dane' ,
		choiceC : 'NewFoundLand',
		correct : 'B',
	}, 
	{
		question : 'Bugs Bunny borrowed the lines ,Here I am!, and ,He dont know me very well, do he?, from whom?',
		choiceA : 'Milton Berle',
		choiceB : 'Lou Costello',
		choiceC : 'Red Skelton',
		correct : 'C',
	}, 
	{
		question : 'In Sponge Bob which character does not work at Krusty Krab?',
		choiceA : 'Plankton',
		choiceB : 'Mr Krabs' ,
		choiceC : 'Spongebob',
		correct : 'A',
	}, 
	{
		question : 'Where does Family Guy take place?',
		choiceA : 'Agrestic',
		choiceB : 'Kaldor',
		choiceC : 'Quahog',
		correct : 'C',
	}, 
	{
		question : 'Which Family Guy character is obsessed with world domination?',
		choiceA : 'Chris',
		choiceB : 'Stewie' ,
		choiceC : 'Brian',
		correct : 'B',
	}, 
	{
		question : 'What is the name of the bar that Peter and his friends usually patronize in Family Guy?',
		choiceA : 'The Drunken Clam',
		choiceB : 'The tipsy Turtle',
		choiceC : 'The Feisty Goat',
		correct : 'A',
	}, 
	{
		question : 'Family Guy storylines are often interrupted by fights between Peter and _______.',
		choiceA : 'Patrick Pewterschmidt',
		choiceB : 'A Giant Chicken' ,
		choiceC : 'Heavy Flo',
		correct : 'B',
	}, 
	{
		question : 'Peter from, family guy, once suffered a stroke after _______.',
		choiceA : 'Climbing A Step Ladder',
		choiceB : 'Trying To Do Math',
		choiceC : 'Eating 30 Hamburgers',
		correct : 'C',
	}, 
	{
		question : 'In Familty Guy, Peter, Glenn, Joe and Cleveland won a costume contest by dressing as ______.',
		choiceA : 'The A-Team',
		choiceB : 'Three Men And A Baby' ,
		choiceC : 'The Ghostbusters',
		correct : 'A',
	}, 
	{
		question : ' Which Family Guy character is a police officer?',
		choiceA : 'Cleveland Brown',
		choiceB : 'Joe Swanson',
		choiceC : 'Glenn Quagmire',
		correct : 'B',
	} 
]

var music = [
	{
		question : 'What did "Weird Al" Yankovic call his album that contained a parody of a song from Michael Jacksons album BAD?',
		choiceA : 'Even Worse',
		choiceB : 'Badder' ,
		choiceC : 'Good',
		correct : 'A',
	}, 
	{
		question : 'Which song did not hit #1 on the Billboard Hot 100?',
		choiceA : 'Bad Blood',
		choiceB : 'Shake It Off' ,
		choiceC : 'You Belong With me',
		correct : 'C',
	}, 
	{
		question : 'Which Michael Jackson album featured the single, Beat It?',
		choiceA : 'Dangerous',
		choiceB : 'Thriller' ,
		choiceC : 'Bad',
		correct : 'B',
	}, 
	{
		question : 'Which of these bands did not originate from the United Kingdom?',
		choiceA : 'Pink Floyd',
		choiceB : 'Queen' ,
		choiceC : 'The Doors',
		correct : 'C',
	}, 
	{
		question : 'Which modern pop artist is known for singing Firework?',
		choiceA : 'Katy Perry',
		choiceB : 'Taylor Swift' ,
		choiceC : 'Adele',
		correct : 'A',
	}, 
	{
		question : 'Who won the 2015 Grammy Award for Record of the Year?',
		choiceA : 'Iggy Azalea',
		choiceB : 'Sam Smith' ,
		choiceC : 'Meghan Trainor',
		correct : 'B',
	}, 
	{
		question : 'Which 90s rapper performed the song Gangstas Paradise?',
		choiceA : 'Snoop Dogg',
		choiceB : 'Ice Cube' ,
		choiceC : 'Coolio',
		correct : 'C',
	}, 
	{
		question : 'What country singer is known for the song Achy Breaky Heart?',
		choiceA : 'Billy Ray Cyrus',
		choiceB : 'Garth Brooks' ,
		choiceC : 'Kenny Chesney',
		correct : 'A',
	}, 
	{
		question : 'Which song by Psy has been viewed over 2 billion times on YouTube?',
		choiceA : 'Daddy',
		choiceB : 'Hangover' ,
		choiceC : 'Gangnam Style',
		correct : 'C',
	}, 
	{
		question : 'Which album features the song Come Together?',
		choiceA : 'Help',
		choiceB : 'Abbey Road' ,
		choiceC : 'Revolver',
		correct : 'B',
	} 
]

var animals = [
{
		question : 'What is a group of owls called',
		choiceA : 'An Army',
		choiceB : 'A Surprise' ,
		choiceC : 'A Parliament',
		correct : 'C',
	}, 
	{
		question : 'How many arms (mistakenly called tentacles) do octopuses have?',
		choiceA : '8',
		choiceB : '10' ,
		choiceC : '6',
		correct : 'A',
	}, 
	{
		question : ' Whats the longest a lobster can live?',
		choiceA : 'Less Than 5 Years',
		choiceB : '30 Years or so' ,
		choiceC : 'More Than 100 Years',
		correct : 'C',
	}, 
	{
		question : 'Which of these animals uses echolocation to navigate?',
		choiceA : 'Mice',
		choiceB : 'Dolphins' ,
		choiceC : 'Pigs',
		correct : 'B',
	}, 
	{
		question : 'What can a Jesus Christ lizard do?',
		choiceA : 'Appear To Come Back From The Dead',
		choiceB : 'Fly' ,
		choiceC : 'Walk on Water',
		correct : 'C',
	}, 
	{
		question : 'Which of the following is NOT a type of antelope?',
		choiceA : 'Impala',
		choiceB : 'Marten' ,
		choiceC : 'Gazelle',
		correct : 'B',
	}, 
	{
		question : 'In what country would you find the worlds northernmost wild monkey population?',
		choiceA : 'Japan',
		choiceB : 'India' ,
		choiceC : 'Spain',
		correct : 'A',
	}, 
	{
		question : 'How many rhinoceroses still exist in the wild?',
		choiceA : '5',
		choiceB : 'More Than A Million' ,
		choiceC : 'About 25,000',
		correct : 'C',
	}, 
	{
		question : 'In what mountain range could you encounter a wild yak?',
		choiceA : 'Alps',
		choiceB : 'Himalayas' ,
		choiceC : 'Rockies',
		correct : 'B',
	}, 
	{
		question : 'What type of animal would you find in an apiary?',
		choiceA : 'Bees',
		choiceB : 'Apes' ,
		choiceC : 'Rabbits',
		correct : 'A',
	}, 
]

var random = [
{
		question : 'How many blue stripes are there on the U.S. flag?',
		choiceA : '6',
		choiceB : '0' ,
		choiceC : '13',
		correct : 'B',
	}, 
	{
		question : 'What is the color of Donald Duck’s bowtie?',
		choiceA : 'Red',
		choiceB : 'Yellow' ,
		choiceC : 'White',
		correct : 'A',
	}, 
	{
		question : 'Which country held the 2016 Summer Olympics?',
		choiceA : 'Italy',
		choiceB : 'China' ,
		choiceC : 'Brazil',
		correct : 'C',
	}, 
	{
		question : 'Which planet is the hottest?',
		choiceA : 'Saturn',
		choiceB : 'Venus' ,
		choiceC : 'Mars',
		correct : 'B',
	}, 
	{
		question : 'According to Forrest Gump, “life was like…”',
		choiceA : 'A Bag Of Lemons',
		choiceB : 'A Box Of Chocolates' ,
		choiceC : 'A lollipop',
		correct : 'B',
	}, 
	{
		question : 'What is the rarest blood type?',
		choiceA : 'B',
		choiceB : 'A' ,
		choiceC : 'AB-Negative',
		correct : 'C',
	}, 
	{
		question : 'How many bones are there in the human body?',
		choiceA : '206',
		choiceB : '205' ,
		choiceC : '209',
		correct : 'A',
	}, 
	{
		question : 'Fe is the chemical symbol for…',
		choiceA : 'Zinc',
		choiceB : 'Iron' ,
		choiceC : 'Hydrogen',
		correct : 'B',
	}, 
	{
		question : 'What is the #1 cookie in the U.S.?',
		choiceA : 'Oreo',
		choiceB : 'Chips Ahoy' ,
		choiceC : 'Girl Scout Thin Mints',
		correct : 'A',
	}, 
	{
		question : 'What does the “E” in Chuck E. Cheese stand for?',
		choiceA : 'Extra',
		choiceB : 'Edward' ,
		choiceC : 'Entertainement',
		correct : 'C',
	}, 
]